export enum UserToUserRelationship {
  NOT_FRIEND= 'NOT_FRIEND',
  FRIEND= 'FRIEND',
  REQUEST_SENT= 'REQUEST_SENT',
  I_FOLLOWER= 'I_FOLLOWER',
  PENDING_ACTION= 'PENDING_ACTION',
  YOUR_FOLLOWER= 'YOUR_FOLLOWER',
}
